<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.truthbean</groupId>
        <artifactId>truthbean-parent</artifactId>
        <version>0.6.2-RELEASE</version>
    </parent>

    <packaging>pom</packaging>

    <artifactId>debbie-cloud</artifactId>
    <version>0.6.2-RELEASE</version>

    <modules>
        <module>dependencies</module>
        <module>boot</module>
        <module>cloud</module>
    </modules>

    <name>debbie-cloud</name>
    <description>debbie cloud</description>
    <url>https://github.com/TruthBean/debbie-cloud</url>

    <properties>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>

        <endorsed.dir>${project.build.directory}/endorsed</endorsed.dir>
        <class.dir>${project.build.directory}/classes</class.dir>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <distributionManagement>
        <snapshotRepository>
            <id>sonatype-snapshots</id>
            <url>https://ossrh-staging-api.central.sonatype.com/content/repositories/snapshots/</url>
        </snapshotRepository>
        <repository>
            <id>sonatype-release</id>
            <url>https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/</url>
        </repository>
    </distributionManagement>

    <licenses>
        <license>
            <name>Mulan PSL v2</name>
            <url>https://github.com/truthbean/debbie-cloud/blob/master/LICENSE</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:git://github.com/truthbean/debbie-cloud.git</connection>
        <url>https://github.com/truthbean/debbie-cloud</url>
        <developerConnection>scm:git:ssh://github.com/truthbean/debbie-cloud.git</developerConnection>
    </scm>
    <developers>
        <developer>
            <id>truthbean</id>
            <name>Rogar·Q (TruthBean)</name>
            <email>truthbean@outlook.com</email>
            <url>https://github.com/truthbean</url>
        </developer>
    </developers>
    <issueManagement>
        <system>github</system>
        <url>https://github.com/truthbean/debbie-cloud/issues</url>
    </issueManagement>

</project>
