<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>debbie-cloud</artifactId>
        <groupId>com.truthbean</groupId>
        <version>0.6.3-RELEASE</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>debbie-all</artifactId>

    <packaging>jar</packaging>

    <properties>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>

    <groupId>com.truthbean</groupId>
    <name>debbie-all</name>
    <version>0.6.3-RELEASE</version>
    <description>debbie all</description>
    <url>https://github.com/TruthBean/debbie-cloud</url>

    <licenses>
        <license>
            <name>Mulan PSL v2</name>
            <url>https://github.com/truthbean/debbie-cloud/blob/master/LICENSE</url>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:git://github.com/truthbean/debbie-cloud.git</connection>
        <url>https://github.com/truthbean/debbie-cloud</url>
        <developerConnection>scm:git:ssh://github.com/truthbean/debbie-cloud.git</developerConnection>
    </scm>
    <developers>
        <developer>
            <id>truthbean</id>
            <name>Rogar·Q (TruthBean)</name>
            <email>truthbean@outlook.com</email>
            <url>https://github.com/truthbean</url>
        </developer>
    </developers>
    <issueManagement>
        <system>github</system>
        <url>https://github.com/truthbean/debbie-cloud/issues</url>
    </issueManagement>

    <dependencies>
        <!-- ======================== truthbean foundation ======================== -->
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>truthbean-core</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>truthbean-transformer</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <!-- ======================== debbie core modules ======================== -->
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-core</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-json</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-xml</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-yaml</artifactId>
            <version>${truthbean.version}</version>
        </dependency>

        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-test</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-agent</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-console</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-mvc</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-aio</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-server</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-httpclient</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-jdbc</artifactId>
            <version>${truthbean.version}</version>
        </dependency>

        <!-- ======================== debbie boot modules ======================== -->

        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-asm</artifactId>
            <version>${truthbean.version}</version>
        </dependency>

        <!-- json -->
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-gson</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-fastjson2</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-jackson</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-fory-json</artifactId>
            <version>${truthbean.version}</version>
        </dependency>

        <!-- datasource -->
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-hikari</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-druid</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-dbcp2</artifactId>
            <version>${truthbean.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>commons-logging</artifactId>
                    <groupId>commons-logging</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-c3p0</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-shardingsphere</artifactId>
            <version>${truthbean.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>httpclient5</artifactId>
                    <groupId>org.apache.httpcomponents.client5</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>httpcore5</artifactId>
                    <groupId>org.apache.httpcomponents.core5</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>commons-compiler</artifactId>
                    <groupId>org.codehaus.janino</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>janino</artifactId>
                    <groupId>org.codehaus.janino</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>commons-logging</artifactId>
                    <groupId>commons-logging</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- orm -->
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-mybatis</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-mybatis-plus</artifactId>
            <version>${truthbean.version}</version>
        </dependency>

        <!-- server -->
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-tomcat</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-netty</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-undertow</artifactId>
            <version>${truthbean.version}</version>
        </dependency>

        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-swagger</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-spring</artifactId>
            <version>${truthbean.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>micrometer-observation</artifactId>
                    <groupId>io.micrometer</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- template engine -->
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-freemarker</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-thymeleaf</artifactId>
            <version>${truthbean.version}</version>
        </dependency>

        <!-- scheduler -->
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-quartz</artifactId>
            <version>${truthbean.version}</version>
        </dependency>

        <!-- messaging -->
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-kafka</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-activemq</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-rocketmq</artifactId>
            <version>${truthbean.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>zstd-jni</artifactId>
                    <groupId>com.github.luben</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>grpc-api</artifactId>
                    <groupId>io.grpc</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>grpc-core</artifactId>
                    <groupId>io.grpc</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>opentelemetry-api</artifactId>
                    <groupId>io.opentelemetry</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>opentelemetry-api-incubator</artifactId>
                    <groupId>io.opentelemetry</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>perfmark-api</artifactId>
                    <groupId>io.perfmark</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>prometheus-metrics-config</artifactId>
                    <groupId>io.prometheus</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>prometheus-metrics-model</artifactId>
                    <groupId>io.prometheus</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>rocketmq-slf4j-api</artifactId>
                    <groupId>io.github.aliyunmq</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>commons-logging</artifactId>
                    <groupId>commons-logging</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-pulsar</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-rabbitmq</artifactId>
            <version>${truthbean.version}</version>
        </dependency>

        <!-- redis -->
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-jedis</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-lettuce</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-redisson</artifactId>
            <version>${truthbean.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>reactor-core</artifactId>
                    <groupId>io.projectreactor</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- nosql -->
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-mongo</artifactId>
            <version>${truthbean.version}</version>
        </dependency>

        <!-- search -->
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-lucene</artifactId>
            <version>${truthbean.version}</version>
        </dependency>

        <!-- grpc -->
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-grpc-server</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-grpc-client</artifactId>
            <version>${truthbean.version}</version>
        </dependency>

        <!-- rpc -->
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-dubbo</artifactId>
            <version>${truthbean.version}</version>
        </dependency>

        <!-- security -->
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-shiro</artifactId>
            <version>${truthbean.version}</version>
        </dependency>

        <!-- monitoring -->
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-metrics</artifactId>
            <version>${truthbean.version}</version>
        </dependency>

        <!-- javafx -->
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-javafx</artifactId>
            <version>${truthbean.version}</version>
        </dependency>

        <!-- zookeeper -->
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-zookeeper</artifactId>
            <version>${truthbean.version}</version>
        </dependency>

        <!-- ======================== debbie cloud modules ======================== -->
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>simple-cloud</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-gateway</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-bus</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-config</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-circuit-breaker</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-consul</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-function</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-kubernetes</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-eureka</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-loadbalancer</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-tracing</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-etcd</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-integration</artifactId>
            <version>${truthbean.version}</version>
        </dependency>

        <!-- ======================== debbie cloud alibaba modules ======================== -->
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-nacos</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-sentinel</artifactId>
            <version>${truthbean.version}</version>
        </dependency>
        <dependency>
            <groupId>com.truthbean</groupId>
            <artifactId>debbie-seata</artifactId>
            <version>${truthbean.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>micrometer-observation</artifactId>
                    <groupId>io.micrometer</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>antlr4-runtime</artifactId>
                    <groupId>org.antlr</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>checker-qual</artifactId>
                    <groupId>org.checkerframework</groupId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <configuration>
                    <transformers>
                        <!-- services -->
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                        <!-- debbie -->
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/com.truthbean.debbie.spi/debbie-properties</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/com.truthbean.debbie.spi/debbie-proxy-handler</resource>
                        </transformer>
                        <!-- spring -->
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/services/spring.factories</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/services/spring.tooling</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/services/spring.schemas</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/services/spring.handlers</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/spring.factories</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/spring.tooling</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/spring.schemas</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/spring.handlers</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/spring-devtools.properties</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/spring-autoconfigure-metadata.properties</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/spring/aot.factories</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>
                                META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
                            </resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/gradle/incremental.annotation.processors</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/terracotta/public-api-types</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/substrate/config/resourcebundles</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/sisu/javax.inject.Named</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/io.netty.versions.properties</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/LICENSE.txt</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/LICENSE.md</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/DEPENDENCIES</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/license.txt</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>LICENSE.txt</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>license.txt</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>LICENSE</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>license</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>NOTICE</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>notice</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>META-INF/LICENSE-notice.md</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                            <resource>THIRD-PARTY</resource>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.ApacheNoticeResourceTransformer">
                            <addHeader>false</addHeader>
                        </transformer>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.ApacheLicenseResourceTransformer"/>
                        <transformer
                                implementation="org.apache.maven.plugins.shade.resource.DontIncludeResourceTransformer">
                            <resource>module-info.class</resource>
                            <resource>versions/9/module-info.class</resource>
                            <resource>META-INF/versions/9/module-info.class</resource>
                            <resource>META-INF/versions/11/module-info.class</resource>
                            <resource>META-INF/*.SF</resource>
                            <resource>META-INF/*.DSA</resource>
                            <resource>META-INF/*.RSA</resource>
                            <resource>META-INF/INFO_BIN</resource>
                            <resource>META-INF/INFO_SRC</resource>
                        </transformer>
                    </transformers>
                </configuration>
                <executions>
                    <execution>
                        <id>assemble-all</id>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <shadedArtifactAttached>true</shadedArtifactAttached>
                            <shadedClassifierName>fat</shadedClassifierName>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <resource>module-info.class</resource>
                                        <resource>versions/9/module-info.class</resource>
                                        <resource>META-INF/versions/9/module-info.class</resource>
                                        <resource>META-INF/versions/11/module-info.class</resource>
                                        <resource>META-INF/*.SF</resource>
                                        <resource>META-INF/*.DSA</resource>
                                        <resource>META-INF/*.RSA</resource>
                                        <resource>META-INF/INFO_BIN</resource>
                                        <resource>META-INF/INFO_SRC</resource>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
