<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>debbie-cloud</artifactId>
        <groupId>com.truthbean</groupId>
        <version>0.6.3-RELEASE</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>debbie-dependencies</artifactId>

    <packaging>pom</packaging>

    <properties>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>

    <groupId>com.truthbean</groupId>
    <name>debbie-dependencies</name>
    <version>0.6.3-RELEASE</version>
    <description>debbie dependencies BOM (Bill of Materials)</description>
    <url>https://github.com/TruthBean/debbie-cloud</url>

    <licenses>
        <license>
            <name>Mulan PSL v2</name>
            <url>https://github.com/truthbean/debbie-cloud/blob/master/LICENSE</url>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:git://github.com/truthbean/debbie-cloud.git</connection>
        <url>https://github.com/truthbean/debbie-cloud</url>
        <developerConnection>scm:git:ssh://github.com/truthbean/debbie-cloud.git</developerConnection>
    </scm>
    <developers>
        <developer>
            <id>truthbean</id>
            <name>Rogar·Q (TruthBean)</name>
            <email>truthbean@outlook.com</email>
            <url>https://github.com/truthbean</url>
        </developer>
    </developers>
    <issueManagement>
        <system>github</system>
        <url>https://github.com/truthbean/debbie-cloud/issues</url>
    </issueManagement>

    <dependencyManagement>
        <dependencies>
            <!-- ======================== truthbean foundation ======================== -->
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>truthbean-core</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>truthbean-transformer</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <!-- ======================== debbie core modules ======================== -->
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-core</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-json</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-xml</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-yaml</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-test</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-agent</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-console</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-mvc</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-aio</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-server</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-httpclient</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-jdbc</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <!-- ======================== debbie boot modules ======================== -->

            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-asm</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <!-- json -->
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-gson</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-fastjson2</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-jackson</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-fory-json</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <!-- datasource -->
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-hikari</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-druid</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-dbcp2</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-c3p0</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-shardingsphere</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <!-- orm -->
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-mybatis</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-mybatis-plus</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <!-- server -->
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-servlet</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-tomcat</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-netty</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-undertow</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-swagger</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-spring</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <!-- template engine -->
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-freemarker</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-thymeleaf</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <!-- scheduler -->
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-quartz</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <!-- messaging -->
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-kafka</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-activemq</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-rocketmq</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-pulsar</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-rabbitmq</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <!-- redis -->
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-jedis</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-lettuce</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-redisson</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <!-- nosql -->
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-mongo</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <!-- search -->
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-lucene</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <!-- grpc -->
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-grpc-server</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-grpc-client</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <!-- rpc -->
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-dubbo</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <!-- security -->
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-shiro</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <!-- monitoring -->
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-metrics</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <!-- javafx -->
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-javafx</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <!-- zookeeper -->
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-zookeeper</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <!-- ======================== debbie cloud modules ======================== -->
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>simple-cloud</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-gateway</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-bus</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-config</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-circuit-breaker</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-consul</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-function</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-kubernetes</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-eureka</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-loadbalancer</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-tracing</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-etcd</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-integration</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

            <!-- ======================== debbie cloud alibaba modules ======================== -->
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-nacos</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-sentinel</artifactId>
                <version>${truthbean.version}</version>
            </dependency>
            <dependency>
                <groupId>com.truthbean</groupId>
                <artifactId>debbie-seata</artifactId>
                <version>${truthbean.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

</project>
